import React from 'react';
import './About.css';
import aboutImg1 from './Images/about1.jpg';
import aboutImg2 from './Images/about2.jpg';
import aboutImg3 from './Images/about3.jpg';
import aboutImg4 from './Images/about4.jpg';
import aboutImg5 from './Images/about5.jpg';
import aboutImg6 from './Images/about6.jpg';


const About = () => {
  return (
    <>
    <div className='aboutHeader'>
    <h1>About Us!</h1>
   <p>
       Welcome to our online store! We are dedicated to providing you with the best shopping
       experience, offering a wide range of high-quality products at affordable prices.
     </p>
    </div>
    <div className="ecommerce-data-container">
   
    <div className='imgSection'>
    <div className='imgSection-up'><img src={aboutImg1}/></div>
    <div className='aboutHeader'>
    <p >
        Our mission is to make online shopping easy, convenient, and enjoyable for our customers.
        Whether you're looking for the latest fashion trends, electronics, home goods, or beauty
        products, we've got you covered.
    </p>
    </div>
   
   
    <div className='imgSection-bottom'>
    <img src={aboutImg2}/>
    <img src={aboutImg3}/>
    <img src={aboutImg4}/>
    <img src={aboutImg5}/>
    </div>
    <div className='imgSection-bottom'>
    <img src={aboutImg2}/>
    <img src={aboutImg3}/>
    
    </div>

    </div>
      <div className="section">
        <h2>Traffic Sources</h2>
        <ul>
          <li>Organic Search</li>
          <li>Paid Advertising</li>
          <li>Social Media</li>
          <li>Referral Traffic</li>
          <li>Direct Visits</li>
        </ul>
      </div>

      <div className="section">
        <h2>Conversion Rate</h2>
        <p>Percentage of visitors who make a purchase</p>
      </div>

      <div className="section">
        <h2>Average Order Value (AOV)</h2>
        <p>Average amount spent by customers in each transaction</p>
      </div>

      <div className="section">
        <h2>Customer Acquisition Cost (CAC)</h2>
        <p>Cost of acquiring a new customer</p>
      </div>

      <div className="section">
        <h2>Customer Lifetime Value (CLV)</h2>
        <p>Estimated total revenue generated by a customer over their entire relationship with the business</p>
      </div>

      <div className="section">
        <h2>Cart Abandonment Rate</h2>
        <p>Percentage of users who abandon their shopping carts without completing a purchase</p>
      </div>

      <div className="section">
        <h2>Product Performance</h2>
        <ul>
          <li>Best-selling products</li>
          <li>Inventory turnover rate</li>
          <li>Product return rate</li>
        </ul>
      </div>

      <div className="section">
        <h2>Customer Satisfaction (CSAT)</h2>
        <p>Level of satisfaction among customers</p>
      </div>

      <div className="section">
        <h2>Return on Investment (ROI)</h2>
        <p>Profitability of marketing campaigns compared to their cost</p>
      </div>

      <div className="section">
        <h2>Mobile vs. Desktop Traffic</h2>
        <ul>
          <li>Percentage of traffic from mobile devices</li>
          <li>Percentage of traffic from desktop devices</li>
        </ul>
      </div>
    </div>
    </>
  );
};

export default About;
