
const productData = [
    {
      "id": 1,
      "name": "T-shirt",
      "category": "Clothing",
      "description": "A comfortable cotton T-shirt for everyday wear.",
      "price": 19.99,
      "image": './images/tshirt.jpg',
    },
    {
      "id": 2,
      "name": "Smartphone",
      "category": "Electronics",
      "description": "A powerful smartphone with the latest features.",
      "price": 399.99,
      "image":  './images/iphone.jpg',
    },
    {
      "id": 3,
      "name": "Running Shoes",
      "category": "Shoes",
      "description": "High-quality running shoes for your active lifestyle.",
      "price": 79.99,
      "image":  './images/shoes.jpg',
    },
    {
      "id": 4,
      "name": "Headphones",
      "category": "Electronics",
      "description": "Wireless headphones for immersive audio experience.",
      "price": 129.99,
      "image":  './images/headphone.jpg',
    },
    {
        "id": 5,
        "name": "Laptop",
        "category": "Electronics",
        "description": "A high-performance laptop for work and entertainment.",
        "price": 999.99,
        "image":  './images/laptop.jpg',
      },
      {
        "id": 6,
        "name": "Dress",
        "category": "Clothing",
        "description": "An elegant dress for special occasions.",
        "price": 49.99,
        "image":  './images/dress.jpg',
      },
      {
        "id": 7,
        "name": "Backpack",
        "category": "Accessories",
        "description": "A stylish and durable backpack for daily use.",
        "price": 39.99,
        "image":  './images/bagpack.jpg',
      },
      {
        "id": 8,
        "name": "Watch",
        "category": "Accessories",
        "description": "A classic wristwatch with a modern touch.",
        "price": 129.99,
        "image":  './images/watch.jpg',
      },
      {
        "id": 9,
        "name": "Sneakers",
        "category": "Shoes",
        "description": "Casual sneakers for everyday comfort.",
        "price": 59.99,
        "image":  './images/Sneakers.jpg',
      },
      {
        "id": 10,
        "name": "Sunglasses",
        "category": "Accessories",
        "description": "Stylish sunglasses to protect your eyes from the sun.",
        "price": 19.99,
        "image":  './images/sunglasses.jpg',
      },
      {
        "id": 11,
        "name": "Wireless Mouse",
        "category": "Electronics",
        "description": "A sleek wireless mouse for improved productivity.",
        "price": 29.99,
        "image":  './images/mouse.jpg',
      },
      {
        "id": 12,
        "name": "Graphic T-shirt",
        "category": "Clothing",
        "description": "A trendy graphic T-shirt to express your style.",
        "price": 24.99,
        "image":  './images/printtshirt.jpg',
      },
      {
        "id": 13,
        "name": "Leather Wallet",
        "category": "Accessories",
        "description": "A classic leather wallet with multiple compartments.",
        "price": 49.99,
        "image":  './images/wallet.jpg',
      },
      {
        "id": 14,
        "name": "Yoga Mat",
        "category": "Sports",
        "description": "A high-quality yoga mat for comfortable workouts.",
        "price": 34.99,
        "image":  './images/yogamat.jpg',
      },
      {
        "id": 15,
        "name": "Wireless Earbuds",
        "category": "Electronics",
        "description": "True wireless earbuds for immersive audio experience.",
        "price": 79.99,
        "image":  './images/earpods.jpg',
      },
      {
        "id": 16,
        "name": "Denim Jeans",
        "category": "Clothing",
        "description": "Classic denim jeans for a timeless look.",
        "price": 59.99,
        "image":  './images/jeans.jpg',
      }
  ];
  
  export default productData;
  